import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";

import { cn } from "@/lib/utils";
import DotPattern from "@/components/magicui/dot-pattern";
import { GlobalProvider } from "./context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <GlobalProvider>
        <body className={inter.className}>
          {children}
          <DotPattern
            className={cn("[mask-image:linear-gradient()] opacity-35 ")}
          />
        </body>
      </GlobalProvider>
    </html>
  );
}
